// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTBCNTT.Models;

#nullable disable

namespace QLTBCNTT.Migrations
{
    [DbContext(typeof(QltbcnttContext))]
    [Migration("20250618161031_AddForgotPasswordFields")]
    partial class AddForgotPasswordFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTBCNTT.Models.BaoTri", b =>
                {
                    b.Property<int>("MaBaotri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_baotri");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaotri"));

                    b.Property<string>("LoaiBaotri")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loai_baotri");

                    b.Property<int>("MaThietbi")
                        .HasColumnType("int")
                        .HasColumnName("ma_thietbi");

                    b.Property<DateOnly>("NgayBaotri")
                        .HasColumnType("date")
                        .HasColumnName("ngay_baotri");

                    b.Property<DateOnly?>("NgayHoanthanh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hoanthanh");

                    b.Property<int?>("NguoiPhuTrach")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_phu_trach");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("da_len_ke_hoach")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaBaotri")
                        .HasName("PK__BaoTri__71BAECF074DACC30");

                    b.HasIndex("MaThietbi");

                    b.HasIndex("NguoiPhuTrach");

                    b.ToTable("BaoTri", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("MaChitietmuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chitietmuon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChitietmuon"));

                    b.Property<int>("MaPhieumuon")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieumuon");

                    b.Property<int>("MaThietbi")
                        .HasColumnType("int")
                        .HasColumnName("ma_thietbi");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.HasKey("MaChitietmuon")
                        .HasName("PK__ChiTietP__003784C759017AB8");

                    b.HasIndex("MaPhieumuon");

                    b.HasIndex("MaThietbi");

                    b.ToTable("ChiTietPhieuMuon", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaChitietnhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chitietnhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChitietnhap"));

                    b.Property<int?>("MaPhieunhap")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieunhap");

                    b.Property<int?>("MaThietbi")
                        .HasColumnType("int")
                        .HasColumnName("ma_thietbi");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.HasKey("MaChitietnhap")
                        .HasName("PK__ChiTietP__52F43C0EC4B4B3BA");

                    b.HasIndex("MaPhieunhap");

                    b.HasIndex("MaThietbi");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaChitietxuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chitietxuat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChitietxuat"));

                    b.Property<int?>("MaPhieuxuat")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieuxuat");

                    b.Property<int?>("MaThietbi")
                        .HasColumnType("int")
                        .HasColumnName("ma_thietbi");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.HasKey("MaChitietxuat")
                        .HasName("PK__ChiTietP__7ABE9F9DE996CCB9");

                    b.HasIndex("MaPhieuxuat");

                    b.HasIndex("MaThietbi");

                    b.ToTable("ChiTietPhieuXuat", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhmuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danhmuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhmuc"));

                    b.Property<string>("TenDanhmuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_danhmuc");

                    b.HasKey("MaDanhmuc")
                        .HasName("PK__DanhMuc__498F58413BFE2CE3");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoidung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoidung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoidung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<int?>("MaPhongban")
                        .HasColumnType("int")
                        .HasColumnName("ma_phongban");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienthoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dienthoai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("nhanvien")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaNguoidung")
                        .HasName("PK__NguoiDun__48823C2E269D1C6E");

                    b.HasIndex("MaPhongban");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__AB6E6164A988638B")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_ncc");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__04FFEEB9F6BFF4FF");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieumuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieumuon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieumuon"));

                    b.Property<DateOnly>("NgayMuon")
                        .HasColumnType("date")
                        .HasColumnName("ngay_muon");

                    b.Property<DateOnly?>("NgayTra")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tra");

                    b.Property<DateOnly>("NgayTraDuKien")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tra_du_kien");

                    b.Property<int?>("NguoiDuyet")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet");

                    b.Property<int>("NguoiMuon")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_muon");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("cho_duyet")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhieumuon")
                        .HasName("PK__PhieuMuo__57BB09F9356571CF");

                    b.HasIndex("NguoiDuyet");

                    b.HasIndex("NguoiMuon");

                    b.ToTable("PhieuMuon", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieunhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieunhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieunhap"));

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<DateOnly>("NgayNhap")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nhap");

                    b.Property<int?>("NguoiNhan")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_nhan");

                    b.HasKey("MaPhieunhap")
                        .HasName("PK__PhieuNha__B3BEEFE977818995");

                    b.HasIndex("MaNcc");

                    b.HasIndex("NguoiNhan");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuxuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieuxuat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuxuat"));

                    b.Property<int?>("MaPhongban")
                        .HasColumnType("int")
                        .HasColumnName("ma_phongban");

                    b.Property<DateOnly>("NgayXuat")
                        .HasColumnType("date")
                        .HasColumnName("ngay_xuat");

                    b.Property<int?>("NguoiNhan")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_nhan");

                    b.HasKey("MaPhieuxuat")
                        .HasName("PK__PhieuXua__36EE59B4BAC0BB96");

                    b.HasIndex("MaPhongban");

                    b.HasIndex("NguoiNhan");

                    b.ToTable("PhieuXuat", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongban")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phongban");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongban"));

                    b.Property<string>("TenPhongban")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_phongban");

                    b.HasKey("MaPhongban")
                        .HasName("PK__PhongBan__4418CABEE5F418E3");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietbi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thietbi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietbi"));

                    b.Property<decimal?>("GiaMua")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("gia_mua");

                    b.Property<int>("MaDanhmuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danhmuc");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<DateOnly?>("NgayMua")
                        .HasColumnType("date")
                        .HasColumnName("ngay_mua");

                    b.Property<string>("SoSerial")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("so_serial");

                    b.Property<string>("TenThietbi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_thietbi");

                    b.Property<int?>("ThoiGianBaohanh")
                        .HasColumnType("int")
                        .HasColumnName("thoi_gian_baohanh");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("con_hang")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaThietbi")
                        .HasName("PK__ThietBi__9B953F6012202AC0");

                    b.HasIndex("MaDanhmuc");

                    b.HasIndex("MaNcc");

                    b.HasIndex(new[] { "SoSerial" }, "UQ__ThietBi__27AAA9B2A05B4E3A")
                        .IsUnique()
                        .HasFilter("[so_serial] IS NOT NULL");

                    b.ToTable("ThietBi", (string)null);
                });

            modelBuilder.Entity("QLTBCNTT.Models.BaoTri", b =>
                {
                    b.HasOne("QLTBCNTT.Models.ThietBi", "MaThietbiNavigation")
                        .WithMany("BaoTris")
                        .HasForeignKey("MaThietbi")
                        .IsRequired()
                        .HasConstraintName("FK__BaoTri__ma_thiet__693CA210");

                    b.HasOne("QLTBCNTT.Models.NguoiDung", "NguoiPhuTrachNavigation")
                        .WithMany("BaoTris")
                        .HasForeignKey("NguoiPhuTrach")
                        .HasConstraintName("FK__BaoTri__nguoi_ph__6A30C649");

                    b.Navigation("MaThietbiNavigation");

                    b.Navigation("NguoiPhuTrachNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("QLTBCNTT.Models.PhieuMuon", "MaPhieumuonNavigation")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaPhieumuon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__ma_ph__619B8048");

                    b.HasOne("QLTBCNTT.Models.ThietBi", "MaThietbiNavigation")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaThietbi")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__ma_th__628FA481");

                    b.Navigation("MaPhieumuonNavigation");

                    b.Navigation("MaThietbiNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLTBCNTT.Models.PhieuNhap", "MaPhieunhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieunhap")
                        .HasConstraintName("FK__ChiTietPh__ma_ph__4E88ABD4");

                    b.HasOne("QLTBCNTT.Models.ThietBi", "MaThietbiNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaThietbi")
                        .HasConstraintName("FK__ChiTietPh__ma_th__4F7CD00D");

                    b.Navigation("MaPhieunhapNavigation");

                    b.Navigation("MaThietbiNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QLTBCNTT.Models.PhieuXuat", "MaPhieuxuatNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuxuat")
                        .HasConstraintName("FK__ChiTietPh__ma_ph__571DF1D5");

                    b.HasOne("QLTBCNTT.Models.ThietBi", "MaThietbiNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaThietbi")
                        .HasConstraintName("FK__ChiTietPh__ma_th__5812160E");

                    b.Navigation("MaPhieuxuatNavigation");

                    b.Navigation("MaThietbiNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.NguoiDung", b =>
                {
                    b.HasOne("QLTBCNTT.Models.PhongBan", "MaPhongbanNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaPhongban")
                        .HasConstraintName("FK__NguoiDung__ma_ph__3C69FB99");

                    b.Navigation("MaPhongbanNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuMuon", b =>
                {
                    b.HasOne("QLTBCNTT.Models.NguoiDung", "NguoiDuyetNavigation")
                        .WithMany("PhieuMuonNguoiDuyetNavigations")
                        .HasForeignKey("NguoiDuyet")
                        .HasConstraintName("FK__PhieuMuon__nguoi__5DCAEF64");

                    b.HasOne("QLTBCNTT.Models.NguoiDung", "NguoiMuonNavigation")
                        .WithMany("PhieuMuonNguoiMuonNavigations")
                        .HasForeignKey("NguoiMuon")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuMuon__nguoi__5CD6CB2B");

                    b.Navigation("NguoiDuyetNavigation");

                    b.Navigation("NguoiMuonNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuNhap", b =>
                {
                    b.HasOne("QLTBCNTT.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__PhieuNhap__ma_nc__4AB81AF0");

                    b.HasOne("QLTBCNTT.Models.NguoiDung", "NguoiNhanNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NguoiNhan")
                        .HasConstraintName("FK__PhieuNhap__nguoi__49C3F6B7");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("NguoiNhanNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuXuat", b =>
                {
                    b.HasOne("QLTBCNTT.Models.PhongBan", "MaPhongbanNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaPhongban")
                        .HasConstraintName("FK__PhieuXuat__ma_ph__52593CB8");

                    b.HasOne("QLTBCNTT.Models.NguoiDung", "NguoiNhanNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("NguoiNhan")
                        .HasConstraintName("FK__PhieuXuat__nguoi__534D60F1");

                    b.Navigation("MaPhongbanNavigation");

                    b.Navigation("NguoiNhanNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.ThietBi", b =>
                {
                    b.HasOne("QLTBCNTT.Models.DanhMuc", "MaDanhmucNavigation")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaDanhmuc")
                        .IsRequired()
                        .HasConstraintName("FK__ThietBi__ma_danh__45F365D3");

                    b.HasOne("QLTBCNTT.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__ThietBi__ma_ncc__46E78A0C");

                    b.Navigation("MaDanhmucNavigation");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("QLTBCNTT.Models.DanhMuc", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QLTBCNTT.Models.NguoiDung", b =>
                {
                    b.Navigation("BaoTris");

                    b.Navigation("PhieuMuonNguoiDuyetNavigations");

                    b.Navigation("PhieuMuonNguoiMuonNavigations");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QLTBCNTT.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QLTBCNTT.Models.PhongBan", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QLTBCNTT.Models.ThietBi", b =>
                {
                    b.Navigation("BaoTris");

                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
